### ISSUE TITLE
Better Error Logs

### ISSUE THREAD

**Issue by athul** [athul/pwcli#8]
The Errors logs just shows Go's usual Panic Output. Maybe we could wrap an abstraction for that. Like 
`Request Error` or `Check the URL/URI and Authentication`

**Comment by gbmor** [comment]
I have this working. Errors are bubbling up instead of panicking, and some of them have added context to the error. I'll wait till PR #9 is finished and merged, before I open a PR.

**Comment by athul** [comment]
🤩
